In [2]:
import numpy as np
import pandas as pd

In [11]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([11,12,13,14,15])
s = pd.DataFrame({"第一列:":s1,"第二列":s2})
df = pd.DataFrame({
    "id":[1,2,3,4,5],
    "name":['a','s','d','f','g'],
    "age":[15,13,14,12,13],
    "score":[88,80,75,45,79]
},index = [1,2,3,4,5],
columns=['name','score','age','id']  #调换列的位置顺序  
)
df

  name  score  age  id
1    a     88   15   1
2    s     80   13   2
3    d     75   14   3
4    f     45   12   4
5    g     79   13   5

In [ ]:
print("行索引:",df.index)
print("列标签:",df.columns)
print(df.dtypes)
print('维度:',df.ndim)
print('形状:',df.shape)
print('元素个数:',df.size)
print('行列转置',df.T)

行索引: Index([1, 2, 3, 4, 5], dtype='int64')
列标签: Index(['name', 'socre', 'age', 'id'], dtype='object')
name     object
socre     int64
age       int64
id        int64
dtype: object
维度: 2
形状: (5, 4)
元素个数: 20
        1   2   3   4   5
name    a   s   d   f   g
socre  88  80  75  45  79
age    15  13  14  12  13
id      1   2   3   4   5

In [12]:
#获取元素   loc iloc at iat
# print(df)
print(df.loc[4])
print(df.iloc[3])
#单个元素
print(df.at[3,'score'])
print(df.iat[2,1])
print(df.loc[3,'score'])

name      f
score    45
age      12
id        4
Name: 4, dtype: object
name      f
score    45
age      12
id        4
Name: 4, dtype: object
75
75
75

In [ ]:
print(df.score)
df.sample(2)

1    88
2    80
3    75
4    45
5    79
Name: score, dtype: int64

  name  score  age  id
2    s     80   13   2
4    f     45   12   4