In [2]:
import pandas as pd

In [ ]:
'''场景： 某班级的学生成绩数据如下，请完成以下任务：
计算每位学生的总分和平均分。
找出数学成绩高于90分或英语成绩高于85分的学生。
按总分从高到低排序,并输出前3名学生。'''

data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}

scores = pd.DataFrame(data)
scores['总分']=scores[['数学','英语','物理']].sum(axis=1)
scores['平均分']=scores[['数学','英语','物理']].mean(axis=1)
scores

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [ ]:
# 找出数学成绩高于90分或英语成绩高于85分的学生。
first = scores[(scores['数学']>90)|(scores['英语']>85)]
print(first[["姓名","数学","英语"]])

   姓名  数学  英语
0  张三  85  90
1  李四  92  88
3  赵六  88  92
4  钱七  95  80

In [25]:
# 按总分从高到低排序,并输出前3名学生。'''
top3 = scores.sort_values(by = '总分',ascending=False).head(3)
print(top3[['姓名','总分']])
w =scores.nlargest(3,columns=["总分"])
print(w)

   姓名   总分
4  钱七  265
3  赵六  265
1  李四  260
   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

In [39]:
'''案例2：销售数据分析
场景： 某公司销售数据如下，请完成以下任务：
计算每种产品的总销售额（销售额 = 单价 × 销量）。
找出销售额最高的产品。
按销售额从高到低排序，并输出所有产品信息。'''

data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}

df = pd.DataFrame(data)
df["销售额"] = df['单价']*df["销量"]
df

  产品名称   单价  销量   销售额
0    A  100  50  5000
1    B  150  30  4500
2    C  200  20  4000
3    D  120  40  4800

In [36]:
df.nlargest(1,columns=['销售额'])
df.loc[df['销售额'].idxmax()]

产品名称       A
单价       100
销量        50
销售额     5000
Name: 0, dtype: object

In [42]:
# 按销售额从高到低排序，并输出所有产品信息。

df.sort_values(by =['销售额'],ascending=False)

  产品名称   单价  销量   销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [44]:
'''案例3：电商用户行为分析
场景： 某电商平台的用户行为数据如下，请完成以下任务：
计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
找出消费金额最高的用户，并输出其所有信息
计算所有用户的平均消费金额（保留2位小数）
统计电子产品的总购买数量'''
data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}

df = pd.DataFrame(data)
df['总消费金额'] = df['商品单价']*df['购买数量']
df

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
0   101    Alice  电子产品  1200     1   1200
1   102      Bob    服饰   300     3    900
2   103  Charlie  电子产品   800     2   1600
3   104    David    家居   150     5    750
4   105      Eve    服饰   200     4    800

In [47]:
# 找出消费金额最高的用户，并输出其所有信息
df.loc[df['总消费金额'].idxmax()]

用户ID         103
用户名      Charlie
商品类别        电子产品
商品单价         800
购买数量           2
总消费金额       1600
Name: 2, dtype: object

In [53]:
# 计算所有用户的平均消费金额（保留2位小数）
a =round(df['总消费金额'].mean(),2)
print(a)

1050.0

In [55]:
# 统计电子产品的总购买数量'''
total = df[df['商品类别']=='电子产品']['购买数量'].sum()
print(total)

3