In [1]:
import pandas as pd

In [9]:
d = pd.Timestamp('2015-05-02 10:22')
print(d)
print(type(d))
print("年: ", d.year)
print("月: ", d.month)
print("日: ", d.day)
print(d.hour, d.minute, d.second)
print("季度: ", d.quarter)
print("是否是月底: ", d.is_month_end)
print('星期几：',d.day_name())
print('转换为天：',d.to_period('D'))
print('转换为季度：',d.to_period('Q'))
print('转换为年度：',d.to_period('Y'))
print('转换为月度：',d.to_period('M'))
print('转换为周维度 ：',d.to_period('W'))

2015-05-02 10:22:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
年:  2015
月:  5
日:  2
10 22 0
季度:  2
是否是月底:  False
星期几： Saturday
转换为天： 2015-05-02
转换为季度： 2015Q2
转换为年度： 2015
转换为月度： 2015-05
转换为周维度 ： 2015-04-27/2015-05-03

In [10]:
#字符串转换为日期类型
a = pd.to_datetime('2015-05-02 10:22')
print(a)
print(type(a))

2015-05-02 10:22:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [17]:
# DataFrame 日期转换

df = pd.DataFrame({
    'sales': [100, 200, 300],
    'date': ['20250601', '20250602', '20250603']
})
df['datetime'] = pd.to_datetime(df['date'])
df['week'] = df['datetime'].dt.day_name()
df

   sales      date   datetime     week
0    100  20250601 2025-06-01   Sunday
1    200  20250602 2025-06-02   Monday
2    300  20250603 2025-06-03  Tuesday

In [28]:
df = pd.read_csv('weather.csv')
df['datetime'] = pd.to_datetime(df['date'])
df

            date  precipitation  temp_max  temp_min  wind  weather   datetime
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle 2012-01-01
1     2012-01-02           10.9      10.6       2.8   4.5     rain 2012-01-02
2     2012-01-03            0.8      11.7       7.2   2.3     rain 2012-01-03
3     2012-01-04           20.3      12.2       5.6   4.7     rain 2012-01-04
4     2012-01-05            1.3       8.9       2.8   6.1     rain 2012-01-05
...          ...            ...       ...       ...   ...      ...        ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain 2015-12-27
1457  2015-12-28            1.5       5.0       1.7   1.3     rain 2015-12-28
1458  2015-12-29            0.0       7.2       0.6   2.6      fog 2015-12-29
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun 2015-12-30
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun 2015-12-31

[1461 rows x 7 columns]

In [ ]:
df = pd.read_csv('weather.csv',parse_dates=['date'])
df['date'].dt.day_name()
df

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]