In [1]:
import pandas as pd
import numpy as np

In [2]:
#导入数据
df = pd.read_csv('penguins.csv')
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [5]:
#数据清洗
print(df.isna().sum())
df.dropna(inplace=True)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [11]:
df.isna().sum()
len(df)

333

In [21]:
#数据特征的构造
df['sex'] = df['sex'].astype('category')
#构造新的数据特征
df['bill_ratio'] = df['bill_length_mm']/df['bill_depth_mm']
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379

In [30]:
#数据分析
#数据分箱- 把体重分为三个等级
labels = ['低','中','高']
df['mass_level']= pd.cut(df['body_mass_g'],bins=3 ,labels=labels)
print(df['mass_level'].value_counts())
#按岛屿和性别分组分析
df.groupby(['sex','island']).agg({
    'body_mass_g':['mean','count']
})

mass_level
低    150
中    128
高     55
Name: count, dtype: int64

C:\Users\86182\AppData\Local\Temp\ipykernel_43872\977786735.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','island']).agg({

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23

In [26]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio,mass_level
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909,低
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115,低
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889,低
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554,低
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767,低