In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('sleep.csv')
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [10]:
#数据清洗
df.isna().sum()
df['sleep_disorder'] = df['sleep_disorder'].fillna(0)

In [21]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,high,low
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,0,124,70
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,0,131,86
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,0,122,70
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,0,124,72
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia,133,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea,118,66
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia,132,80
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia,125,76
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea,130,75
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,Sleep Apnea,118,70

In [22]:
#数据特征的构造
df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
df[['high','low']] = df['blood_pressure'].str.split('/',expand = True)

In [23]:
#睡眠质量的分箱
label = ['差','中','优']
df['quality_evel'] = pd.cut(df['sleep_quality'],
                            bins=3,labels= label)

In [25]:
#数据统计和分析
print(df['bmi_category'].value_counts())

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

In [24]:
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,high,low,quality_evel
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,0,124,70,中
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,0,131,86,中
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,0,122,70,中
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,0,124,72,优
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia,133,78,优

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    category
 2   age                      400 non-null    int64
 3   occupation               400 non-null    category
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    category
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           400 non-null    object
dtypes: category(3), float64(2), int64(6), object(2)
memory usage: 33.1+ KB